### ISSUE TITLE
Doesn't work - loads fine tho

### ISSUE THREAD

**Issue by Bullzai** [Kailo97/sm-blindhook#5]
Hi,

The extension loads just fine for CSGO (v1.5 linux).
Simplest plugins like this - https://hlmod.net/resources/noteamflash.3504/ loads fine as well, but they don't work. Tried printing to console/chat on CS_OnBlindPlayer, but nothing happens, meaning it never gets called when the user gets blinded by a flashbang grenade.

Tested on 2 vanilla servers (newest stable SM & MM) also - no errors in console/logs, just doesn't work. If you need any more info or tests to be done, please let me know!

OS: CentOS 8 if that matters

**Comment by Kailo97** [comment]
Hi, 

I don't receive any issues besides you. I'll check if gamedata is outdate, but suppose it's problem local for you.
1st line troubleshooting:
1. check logs - done
2. check extensions list (Is even loaded?) `sm exts list`
3. check gamedata file, attach this file from your server `addons/sourcemod/gamedata/blindhook.games.txt`

**Comment by Bullzai** [comment]
Hey Kailo!

Yes, I've checked that the extension is loaded & that the plugin is as well. No errors whatsoever, everything is loaded.

This is the gamedata content:

[blindhook.games.txt](https://github.com/Kailo97/sm-blindhook/files/12209073/blindhook.games.txt)

Tried using Maza's plugin, creating my own using that CS_OnBlindPlayer hook just to print some text to see if it's even being called, to no avail. 

Maybe you could add me on Discord - **bullzai** and we could troubleshoot it live through there?

The most bazar thing it doesn't work on fresh vanilla server as well. It says everything is loaded, but whenever player is flashed, CS_OnBlindPlayer seems to do nothing.
